name: CI
"on":
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Installing Dependencies
        run: yarn install
      - name: Test
        run: yarn test
